# Site settings
title: My Blog
SEOTitle: Jacky的博客 | My Blog
header-img: img/post-bg-desk.jpg
email: 1126651826@qq.com
description: "一个人，一座城，没有你的剧本，不完整的人生."
keyword: "Blog, Jacky的博客, vue, front, html, css, javascript"
url: "http://jacky010.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Jacky010/Jacky010.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "蜀道难，难于上青天"
sidebar-avatar:       # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    Jacky010
facebook_username:  
jianshu_username:   
#twitter_username:   




# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: jacky010

# Gitalk
gitalk:
  enable: true               #是否开启Gitalk评论
  clientID: 9789176b2e8e36191a3b    #生成的clientID
  clientSecret: 5c6fbfd5fcf53d405cf35ade868b441c0f540435        #生成的clientSecret
  repo: Jacky010.github.io    #仓库名称
  owner: Jacky010             #github用户名
  admin: Jacky010
  distractionFreeMode: true   #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f8969f47d2b690cfc928736276c1fc38

# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain:               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub",
        href: "https://github.com/Jacky010"
    },{
        title: "Email",
        href: "https://mail.qq.com/"
    },{
        title: "CSDN",
        href: "https://www.csdn.net/"
    },{
        title: "Vue Developer",
        href: "https://cn.vuejs.org/"
    }
]
